# MongoDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dev
  labels:
    app: mongo-db 
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=                  # Base64: admin
  MONGO_PASSWORD: cGFzc3dvcmQxMjM=          # Base64: password123
