# MongoDB StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: dev
  labels:
    app: mongo-db

spec:
  serviceName: mongodb-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db

    spec:
      containers:
      - name: mongodb
        image: mongo:8.0
        imagePullPolicy: IfNotPresent
        args:
          - "--auth"
          - "--wiredTigerCacheSizeGB"
          - "0.25"
          - "--bind_ip_all"
        ports:
        - containerPort: 27017

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_PASSWORD
        
        # Database name for initialization
        - name: MONGO_INITDB_DATABASE
          value: "todo-app-db"

        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
          subPath: mongodb

        resources:
          requests:
            memory: "768Mi"
            cpu: "500m"
          limits:
            memory: "1500Mi"
            cpu: "1000m"

        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 20
          periodSeconds: 15

volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 5Gi
